### ISSUE TITLE
Binderfs could not be patched for kernel 4.4.xxx

### ISSUE THREAD

**Issue by ubuntu2029** [Anbox-halium/anbox-halium#2]
Hi developer,

I tested your installer script, but I failed to make it working.  My device is Oneplus 5t(dumpling), it is based on Halium-9. Kernel version 4.4.153.
I could patch binder and ashmem for kernel, but unfortunately I could not patch binderfs, just because only ver 5.xx.xx could be found in deriver/android/. Could you advise what we could do for the next? Many thanks.

**Comment by erfanoabdi** [comment]
binderfs is not needed on halium 9 and 10 devices
also please don't try yet everything is still WIP

**Comment by nfsprodriver** [comment]
@ubuntu2029 how did you patch the kernel btw? I didn't do this before 😅

**Comment by erfanoabdi** [comment]
@nfsprodriver checkout this https://github.com/Anbox-halium/anbox-halium#patching-kernel
run the patcher over your defconfig

**Comment by ubuntu2029** [comment]
> @ubuntu2029 how did you patch the kernel btw? I didn't do this before 😅

it depends on your device, for example my device is Oneplus 5t and my code is located in /opt/halium/

**Comment by nfsprodriver** [comment]
Basically that's my question. Where can I find this kernel? Do I need to clone the android_kernel_..._8998 (I also have OP5, but cheeseburger) and there is on file?

**Comment by ubuntu2029** [comment]
> Basically that's my question. Where can I find this defconfig? Do I need to clone the android_kernel_..._8998 (I also have OP5, but cheeseburger) and there is one file?

It is the same file,kernel/oneplus/msm8998/arch/arm64/configs/lineage_oneplus5_defconfig .

Assume, if you do not have the source code ,you may execute repo init -u https://github.com/Halium/android.git -b Halium-9.0 and then repo sync . You will get it

**Comment by nfsprodriver** [comment]
Thanks! I did this once before, but I need to reinvestigate into it to finally build the patched kernel.

**Comment by ubuntu2029** [comment]
> binderfs is not needed on halium 9 and 10 devices
> also please don't try yet everything is still WIP

It seems the webview could not be working correctly. A lot of news client was failed for loading web contents
